package io.gatm.auth

import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

/**
 * API token and user name generated by grails-spring-security-rest plugin.
 *
 * @author Minhaj
 */
@ToString(includeNames = true, includeFields = true)
@EqualsAndHashCode
class AuthenticationToken {
    String token
    String username
}